"use client";
import Link from "next/link";
import { Search } from "lucide-react";
import { useEffect, useState } from "react";
import { apiFetch } from "@/app/_lib/api";
type Proforma = { id: number; numero?: string | null; nombre_cliente: string; estado: string; fecha: string; total: string; vendedor?: { nombre: string } };
type Meta = { current_page: number; last_page: number };
export default function ProformasPage() { const [items, setItems] = useState<Proforma[]>([]); const [search, setSearch] = useState(""); const [estado, setEstado] = useState(""); const [page, setPage] = useState(1); const [meta, setMeta] = useState<Meta>({ current_page: 1, last_page: 1 }); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { const timer = window.setTimeout(async () => { setLoading(true); try { const response = await apiFetch(`/proformas?search=${encodeURIComponent(search)}&estado=${estado}&page=${page}&per_page=15`); const data = await response.json().catch(() => null); if (!response.ok) throw new Error(); setItems(data?.data ?? []); setMeta(data?.meta ?? { current_page: page, last_page: 1 }); } catch { setError("No se pudieron cargar las proformas."); } finally { setLoading(false); } }, 250); return () => window.clearTimeout(timer); }, [search, estado, page]);
  return <div className="w-full max-w-full overflow-x-hidden bg-[#456f89] px-3 py-4 text-[#08264d] sm:px-8 sm:py-7"><header className="mb-6 flex flex-col gap-4"><div className="flex items-center justify-between gap-3"><div><h1 className="text-[42px] font-extrabold leading-none text-white sm:text-[56px]">Proformas</h1><p className="mt-2 text-sm font-medium text-white/85">Cotizaciones comerciales y análisis de rentabilidad.</p></div><Link href="/proformas/nueva" className="rounded bg-white px-4 py-2 text-sm font-bold">Nueva</Link></div><div className="flex flex-col gap-3 sm:flex-row"><div className="relative h-11 flex-1"><Search className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2" /><input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Buscar número o cliente" className="h-full w-full rounded bg-white pl-10 pr-3 text-sm" /></div><select value={estado} onChange={(event) => { setEstado(event.target.value); setPage(1); }} className="h-11 rounded bg-white px-3 text-sm"><option value="">Todos los estados</option>{["borrador", "emitida", "enviada", "aceptada", "rechazada", "vencida"].map((item) => <option key={item} value={item}>{item}</option>)}</select></div></header>{error ? <p className="mb-4 rounded bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p> : null}<section className="rounded bg-[#e9eef1] p-4 shadow-lg">{loading ? <p className="p-5 text-sm font-semibold">Cargando...</p> : <div className="space-y-3">{items.map((item) => <Link key={item.id} href={`/proformas/${item.id}`} className="block rounded bg-white p-4 transition hover:bg-white/80"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold">{item.numero ?? "Borrador"} · {item.nombre_cliente}</p><p className="text-xs text-[#456f89]">{item.fecha} · {item.vendedor?.nombre ?? "—"}</p></div><div className="text-right text-sm"><p className="font-bold capitalize">{item.estado}</p><p>Total: C$ {Number(item.total ?? 0).toFixed(2)}</p></div></div></Link>)}{items.length === 0 ? <p className="p-5 text-center text-sm">No hay proformas.</p> : null}</div>}<nav className="mt-4 flex items-center justify-between text-sm font-bold"><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)} className="rounded bg-white px-3 py-2 disabled:opacity-40">Anterior</button><span>Página {meta.current_page} de {meta.last_page}</span><button disabled={page >= meta.last_page} onClick={() => setPage((value) => value + 1)} className="rounded bg-white px-3 py-2 disabled:opacity-40">Siguiente</button></nav></section></div>; }
