"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { apiFetch } from "@/app/_lib/api";
import { useCatalogCapabilities } from "@/app/_components/catalog-permissions-provider";
type Pedido = { id: number; numero: string; proforma_numero: string | null; nombre_cliente: string; estado: string; fecha_pedido: string; progreso: { porcentaje_materiales: number; porcentaje_produccion: number }; vendedor?: { nombre: string } };
type Meta = { current_page: number; last_page: number };
export default function PedidosPage() {
  const { canView } = useCatalogCapabilities("/pedidos"); const [items,setItems]=useState<Pedido[]>([]); const [search,setSearch]=useState(""); const [estado,setEstado]=useState(""); const [page,setPage]=useState(1); const [meta,setMeta]=useState<Meta>({current_page:1,last_page:1}); const [error,setError]=useState("");
  useEffect(()=>{const timer=window.setTimeout(async()=>{const response=await apiFetch("/pedidos?search="+encodeURIComponent(search)+"&estado="+estado+"&page="+page+"&per_page=15"); const data=await response.json().catch(()=>null); if(!response.ok){setError(data?.message??"No se pudieron cargar los pedidos.");return;} setItems(data?.data??[]);setMeta(data?.meta??{current_page:page,last_page:1});},250);return()=>window.clearTimeout(timer);},[search,estado,page]);
  if(!canView)return null;
  return <div className="w-full bg-[#456f89] px-3 py-4 text-[#08264d] sm:px-8 sm:py-7"><header className="mb-6"><h1 className="text-3xl font-extrabold text-white sm:text-5xl">Pedidos</h1><p className="mt-2 text-sm text-white/85">Seguimiento de pedidos aceptados.</p><div className="mt-4 flex flex-col gap-3 sm:flex-row"><input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Buscar pedido, proforma o cliente" className="h-11 flex-1 rounded bg-white px-3 text-sm"/><select value={estado} onChange={e=>{setEstado(e.target.value);setPage(1)}} className="h-11 rounded bg-white px-3 text-sm"><option value="">Todos los estados</option>{["pendiente","materiales_pendientes","materiales_listos","en_produccion","terminado","cancelado"].map(value=><option key={value} value={value}>{value}</option>)}</select></div></header>{error?<p className="mb-4 rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>:null}<section className="rounded bg-[#e9eef1] p-4 shadow-lg"><div className="space-y-3">{items.map(item=><Link href={"/pedidos/"+item.id} key={item.id} className="block rounded bg-white p-4 hover:bg-white/80"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold">{item.numero} · {item.nombre_cliente}</p><p className="text-xs text-[#456f89]">Proforma: {item.proforma_numero??"—"} · {item.fecha_pedido} · {item.vendedor?.nombre??"—"}</p></div><div className="text-right text-sm"><p className="font-bold capitalize">{item.estado.replaceAll("_"," ")}</p><p>Materiales {item.progreso?.porcentaje_materiales??0}% · Producción {item.progreso?.porcentaje_produccion??0}%</p></div></div></Link>)}{items.length===0?<p className="p-5 text-center text-sm">No hay pedidos.</p>:null}</div><nav className="mt-4 flex items-center justify-between text-sm font-bold"><button disabled={page<=1} onClick={()=>setPage(value=>value-1)} className="rounded bg-white px-3 py-2 disabled:opacity-40">Anterior</button><span>Página {meta.current_page} de {meta.last_page}</span><button disabled={page>=meta.last_page} onClick={()=>setPage(value=>value+1)} className="rounded bg-white px-3 py-2 disabled:opacity-40">Siguiente</button></nav></section></div>;
}
